apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
- namespace.yaml
patches:
- path: rollout-patch.yaml
configMapGenerator:
- behavior: merge
  literals:
  - ENVIRONMENT=dev
  name: gitops-demo-app-config
images:
- name: ghcr.io/ejoh-hosea/gitops-demo-app
  newName: ghcr.io/ejoh-hosea/gitops-demo-app
  newTag: cc86d1c9
- name: ghcr.io/ejoh-hosea/multi-env-gitops-pipeline
  newName: ghcr.io/ejoh-hosea/multi-env-gitops-pipeline
  newTag: 65569c9d
