apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: rollout-patch.yaml
configMapGenerator:
  - name: gitops-demo-app-config
    behavior: merge
    literals:
      - ENVIRONMENT=dev
images:
  - name: ghcr.io/ejoh-hosea/gitops-demo-app
    newTag: "dev-placeholder" # <-- overwritten automatically by CI on every merge to main
